name: Process release branch

on:
  create:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@master
        with:
          ref: master

      - id: release
        run: echo ::set-output name=version::$( echo ${{ github.ref }} | cut -d '/' -f 3 )

      - id: branch
        run: echo ::set-output name=ref::${{ format('auto/pr/{0}/{1}', github.run_number, github.run_attempt) }}

      - uses: crazy-max/ghaction-import-gpg@8c43807e82148a7bafc633cc9584d04bf54be8d0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_committer_name: ChipInside BOT
          git_committer_email: ti@chipinside.com.br

      - id: generate-token
        name: Create App Token
        uses: tibdex/github-app-token@cdb5bfda87db263e4be5c6f570c4c39611ee952a
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout new branch
        run: git checkout -b ${{ steps.branch.outputs.ref }}

      - id: change
        name: Change something
        run: date +%s > timestamp

      - id: commit
        name: Change something
        run: git commit --allow-empty -m "New branch for release ${{ steps.release.outputs.version }}"

      - id: commit
        name: Change something
        run: git push --force --set-upstream origin ${{ steps.branch.outputs.ref }}

      - id: pr
        name: Create PR to master
        uses: emiliopedrollo/create-pull-request@v1.0.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base: master
          head: ${{ steps.branch.outputs.ref }}
          title: ${{ format('[AUTO] Release {0}', steps.tag.outputs.release) }}
          body: Auytomatcally generated by Chipinside MultiPurpose Tool when creating a new release branch

      - name: print output
        run: echo CREATE EPHEMERAL ENV FOR PR ${{ steps.pr.outputs.pull-request-number }}
